package com.example.intervaltimer.core.constants

object Constants {
    const val ACTION_SERVICE_START = "ACTION_SERVICE_START"
    const val ACTION_SERVICE_STOP = "ACTION_SERVICE_STOP"
    const val ACTION_SERVICE_CANCEL = "ACTION_SERVICE_CANCEL"

    const val INTERVAL_TIMER_STATE = "INTERVAL_TIMER_STATE"

    const val NOTIFICATION_CHANNEL_ID = "INTERVAL_TIMER_NOTIFICATION_ID"
    const val NOTIFICATION_CHANNEL_NAME = "INTERVAL_TIMER_NOTIFICATION"
    const val NOTIFICATION_ID = 10

    const val CLICK_REQUEST_CODE = 100
    const val CANCEL_REQUEST_CODE = 101
    const val STOP_REQUEST_CODE = 102
    const val RESUME_REQUEST_CODE = 103
}